name: mobile_operator_info
description: "A Flutter plugin for retrieving mobile operator information such as operator name, mobile country code (MCC), and mobile network code (MNC)."
version: 1.0.0
homepage: https://github.com/safchemist/mobile_operator_info

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.safchemist.mobile_operator_info
        pluginClass: MobileOperatorInfoPlugin
      ios:
        pluginClass: MobileOperatorInfoPlugin
